/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ActrNode {
  /**
   * Start the node and return ActrRef.
   *
   * # Safety
   *
   * This function is unsafe because it takes ownership of the internal node and
   * starts the actor runtime. It must only be called once.
   */
  start(): Promise<ActrRef>
}

export declare class ActrRef {
  /** Get the actor ID. */
  actorId(): ActrId
  /** Discover actors of the given type. */
  discover(targetType: ActrType, count: number): Promise<Array<ActrId>>
  /** Call remote actor (RPC). */
  call(routeKey: string, payloadType: PayloadType, requestPayload: Buffer, timeoutMs: number): Promise<Buffer>
  /** Send one-way message (fire-and-forget). */
  tell(routeKey: string, payloadType: PayloadType, messagePayload: Buffer): Promise<void>
  /** Trigger shutdown. */
  shutdown(): void
  /** Wait for shutdown to complete. */
  waitForShutdown(): Promise<void>
  /** Check if shutdown is in progress. */
  isShuttingDown(): boolean
}

export declare class ActrSystem {
  /** Create ActrSystem from a config file path. */
  static fromFile(configPath: string): Promise<ActrSystem>
  /** Attach a workload and create ActrNode. */
  attach(callback: object): ActrNode
}

export declare class ContextBridge {
  /** Call remote actor. */
  callRaw(target: ActrId, routeKey: string, payloadType: PayloadType, payload: Buffer, timeoutMs: number): Promise<Buffer>
  /** Send one-way message. */
  tellRaw(target: ActrId, routeKey: string, payloadType: PayloadType, payload: Buffer): Promise<void>
  /** Discover an actor of the given type. */
  discover(targetType: ActrType): Promise<ActrId>
  /** Send DataStream chunk to target. */
  sendDataStream(target: ActrId, chunk: DataStream): Promise<void>
  /** Register a callback for an incoming DataStream. */
  registerStream(streamId: string, callback: (err: Error | null, signal: StreamSignal) => void): Promise<void>
  /** Unregister a DataStream callback. */
  unregisterStream(streamId: string): Promise<void>
  /** Get the current RPC call ID from the runtime context. */
  callId(): ActrId | null
}

export interface ActrId {
  realm: Realm
  serialNumber: number
  type: ActrType
}

export interface ActrType {
  manufacturer: string
  name: string
}

export interface DataStream {
  streamId: string
  sequence: number
  payload: Buffer
  metadata: Array<MetadataEntry>
  timestampMs?: number
}

export interface MetadataEntry {
  key: string
  value: string
}

export declare const enum PayloadType {
  RpcReliable = 0,
  RpcSignal = 1,
  StreamReliable = 2,
  StreamLatencyFirst = 3,
  MediaRtp = 4
}

export interface Realm {
  realmId: number
}

export interface RpcEnvelopeBridge {
  routeKey: string
  payload: Buffer
  requestId: string
}

export interface StreamSignal {
  chunk: DataStream
  sender: ActrId
}
